version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "424-longest-repeating-character-replacement"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
