version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "./projects/leetcode/849-maximize-distance-to-closest-person"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
