version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "./projects/leetcode/125-valid-palindrome"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
