version: "3"

tasks:
  git:
    desc: fast commit
    cmds:
      - git add .
      - git commit -m "235-lowest-common-ancestore-of-bin-tree"
      - git push -u origin $(git rev-parse --abbrev-ref HEAD)
